/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timers.h"

//Variables

uint_8 score = 0;
uint_8 add_points_1 = 0;
uint_8 current_time = 0;

#define uint_8 point_val_1 = 100;
#define uint_8 point_val_2 = 200;
#define uint_8 point_val_3 = 500;
#define uint_8 multi_duration_1 = 5000;
#define uint_8 multi_duration_2 = 5000;

void multiplier_reset(){
	multiplier = 1;
}

int main(void){

	trigger_prescaler(0x1F40 - 1);

	while(end_game != 1){

		if(game_start == 1){
			game_start = 0;
			game_timer(300); //Set in seconds.
		}



		if(sen_mx2 == 1){
			multipler = 2;
			mult_timer(&multiplier_reset, multi_duration_1);
			sen_mx2 = 0;
			//clear flag from sensor reading as high? If turns off auto, leave alone. (Is using falling edge possible for sensor reading? avoids multiple triggers)
		}

		if(sen_mx5 == 1){
			multiplerx5 = 5;
			mult_timer(&multiplier_reset, multi_duration_2);
			sen_mx5 = 0;
			//clear flag from sensor reading as high? If turns off auto, leave alone. (Is using falling edge possible for sensor reading? avoids multiple triggers)

			//clear lower multipliers
		}


		//Score handling

		if(sen_pnt_1 == 1){
			score += point_val_1 * multiplier;
			sen_pnt_1 = 0;
		}
		if (sen_pnt_2 == 1){
			score += point_val_2 * multiplier;
			sen_pnt_2 = 0;
		}
		if (sen_pnt_3 == 1){
			score += point_val_3 * multiplier;
			sen_pnt_3 = 0;
		}

		//Transmit Score (& Game time? & Current multiplier?)

		current_time = get_game_time();













	}
	//Output Game Over


}
